[font]
size = 20.0

[window]
padding = { x = 2, y = 2 }
decorations = "Full"
startup_mode = "Maximized"
opacity = 0.7
dynamic_padding = true  # Opcional: ajusta el padding dinámicamente

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500


[font.normal]
family = "IosevkaTerm NF"


[env]
TERM = "xterm-256color"
